### ISSUE TITLE
Sparse matrix functionality

### ISSUE THREAD

**Issue by MikeCain** [nwtnni/hungarian#2]
Hi!
Would you consider providing an implementation that handles sparse matrix representations as well?

**Comment by nwtnni** [comment]
Hello!

Unfortunately my implementation is pretty tightly coupled to [ndarray](https://docs.rs/ndarray/0.13.1/ndarray/), which doesn't support sparse matrices as of now. But I did dig around a bit and found that the [`pathfinding`](https://github.com/samueltardieu/pathfinding) crate has a [better implementation](https://docs.rs/pathfinding/2.0.4/pathfinding/kuhn_munkres/index.html), with a [`Weights`](https://docs.rs/pathfinding/2.0.4/pathfinding/kuhn_munkres/trait.Weights.html) trait that you could implement for a `HashMap<Point, Cost>` (or equivalent).

Actually, I ran some benchmarks and `pathfinding`'s implementation is significantly faster. Since this is an old hobby project, and `pathfinding` seems like it's being more actively maintained, I'll add a note to the README indicating that it's probably a better choice.

**Comment by MikeCain** [comment]
That's fine.  Thanks for the feedback the interesting idea!
